spring.application.name=backend

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5433/devpilot}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false
# =========================
# XKiro Chat
# =========================
spring.ai.model.chat=openai

spring.ai.openai.chat.base-url=https://api.xkiro.com/v1
spring.ai.openai.chat.api-key= {your key}
spring.ai.openai.chat.model=qwen/qwen3.8-omni-flash:free

# Jina Embeddings
spring.ai.model.embedding=openai
spring.ai.openai.embedding.base-url=https://api.jina.ai/v1
spring.ai.openai.embedding.api-key={your key}
spring.ai.openai.embedding.model=jina-embeddings-v2-base-code
spring.ai.openai.embedding.encoding-format=base64

# =========================
# Disable unused OpenAI models
# =========================
spring.ai.model.audio.speech=none
spring.ai.model.audio.transcription=none
spring.ai.model.image=none
spring.ai.model.moderation=none
#pgvector
spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.dimensions=768
spring.ai.vectorstore.pgvector.index-type=HNSW
spring.ai.vectorstore.pgvector.distance-type=COSINE_DISTANCE
#1536
# Github OAuth2
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:Ov23liyooFoY9BTn2E6T}
spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:624aa5d0dfc2a4426b4896e6f979834abf643e5b}
spring.security.oauth2.client.registration.github.scope=read:user,repo
spring.security.oauth2.client.provider.github.user-name-attribute=id

server.servlet.session.cookie.name=DEVPILOT_SESSION
server.servlet.session.cookie.http-only=true
server.servlet.session.cookie.same-site=lax
server.servlet.session.timeout=7d

# App settings
app.frontend-url=${FRONTEND_URL:http://localhost:3000}
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:3000}
app.token-encryptor-password=${TOKEN_ENCRYPTOR_PASSWORD:devpilot-local-encrypt-key-change-me}
app.token-encryptor-salt=${TOKEN_ENCRYPTOR_SALT:deadbeefcafebabe}
app.indexing.max-file-bytes=102400
app.indexing.chunk-size=800
app.indexing.chunk-overlap=100
app.github.api-delay-ms=50

